# Generated by Django 2.2.2 on 2019-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Plane',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='plane',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_comp1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_comp2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_role1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_role2',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_apprentice',
            field=models.BooleanField(default=False, verbose_name='Apprentice'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_mage',
            field=models.BooleanField(default=False, verbose_name='Mage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_normal',
            field=models.BooleanField(default=False, verbose_name='Normal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_planeswalker',
            field=models.BooleanField(default=False, verbose_name='Planeswalker'),
        ),
    ]
