# Generated by Django 2.2.2 on 2019-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190619_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('R', 'Red'), ('G', 'Green'), ('BU', 'Blue')], default='B', max_length=2)),
            ],
        ),
    ]
